import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/Providres/Provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" data-theme="light">
        <body>
          <Toaster position="top-right" richColors />
          {children}
        </body>
      </html>
    </Providers>
  );
}
