import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/Providres/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" data-theme="light">
        <body>{children}</body>
      </html>
    </Providers>
  );
}
